#!/bin/bash
export XDG_CONFIG_HOME="$HOME/.config"
export STUFF="$HOME/personal_stuff"

export JAVA_HOME=/usr/lib64/java
export MANPATH="${MANPATH}:${JAVA_HOME}/man:\
/opt/texlive/texmf-dist/doc/man"
export CLASSPATH=".:/opt/antlr/antlr-4.4-complete.jar:$CLASSPATH"
export PATH="${PATH}:/opt/texlive/bin/x86_64-linux"

# Enable color in grep
export GREP_OPTIONS='--color=auto'

export HISTCONTROL=ignoredups
export ANA=jake@anapnea.net #xn--phnix-ibb.net
export VORTEX=vortex.labs.overthewire.org

export LESS='--ignore-case --raw-control-chars'
export PAGER="/bin/sh -c \"unset PAGER;col -b -x | \
    vim -R -c 'set ft=man nomod nolist' -c 'map q :q<CR>' \
    -c 'map <SPACE> <C-D>' -c 'map b <C-U>' \
    -c 'nmap K :Man <C-R>=expand(\\\"<cword>\\\")<CR><CR>' -\""
export EDITOR='vim'
export __GIT_PROMPT_DIR=$STUFF/zsh/

#Export LS_COLORS
eval `dircolors $HOME/.dircolors`

#set it mapping without problems
#setxkbmap -layout it -model pc104

stty -ixon
