#!/bin/bash
git submodule add http://github.com/mileszs/ack.vim.git vim/bundle/ack.vim
git submodule add http://github.com/vim-scripts/c.vim.git vim/bundle/c.vim
git submodule add http://github.com/mattn/calendar-vim.git vim/bundle/calendar-vim
git submodule add http://github.com/mattn/emmet-vim.git vim/bundle/emmet-vim
git submodule add http://github.com/othree/html5.vim.git vim/bundle/html5.vim
git submodule add http://github.com/davidhalter/jedi-vim.git vim/bundle/jedi-vim
git submodule add http://github.com/scrooloose/syntastic.git vim/bundle/syntastic
git submodule add http://github.com/tomtom/tlib_vim.git vim/bundle/tlib_vim
git submodule add http://github.com/MarcWeber/vim-addon-mw-utils.git vim/bundle/vim-addon-mw-utils
git submodule add http://github.com/garbas/vim-snipmate.git vim/bundle/vim-snipmate
git submodule add http://github.com/honza/vim-snippets.git vim/bundle/vim-snippets
git submodule add http://github.com/tpope/vim-pathogen.git vim/bundle/vim-pathogen
git submodule add http://github.com/vhdirk/vim-cmake.git vim/bundle/vim-cmake
git submodule add http://github.com/altercation/vim-colors-solarized.git vim/bundle/vim-colors-solarized
git submodule add http://github.com/tpope/vim-fugitive.git vim/bundle/vim-fugitive
git submodule add http://github.com/tpope/vim-surround.git vim/bundle/vim-surround
git submodule init && git submodule update --init --recursive
git submodule foreach git pull origin master:master
